### ISSUE TITLE
panic when path to files is CWD

### ISSUE THREAD

**Issue by rafaelespinoza** [rafaelespinoza/godfish#1]
In this example, the CWD is `/app`.

```
/app # cat .godfish.json
{
        "path_to_files": "/app"
}
/app # ./godfish info
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/rafaelespinoza/godfish.parseMigration(0xc0000143d3, 0xd, 0x64, 0xc00000c400, 0x64, 0x0)
        /go/pkg/mod/github.com/rafaelespinoza/godfish@v0.0.0-20200122053657-81bb649862dd/godfish.go:82 +0x414
github.com/rafaelespinoza/godfish.listAvailableMigrations(0xc0000143bc, 0x4, 0x456401, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/rafaelespinoza/godfish@v0.0.0-20200122053657-81bb649862dd/godfish.go:610 +0x283
github.com/rafaelespinoza/godfish.listMigrationsToApply(0x72d160, 0xc00009a000, 0xc0000143bc, 0x4, 0x1, 0x0, 0x0, 0xc000018001, 0xc000012028, 0xc000014058, ...)
        /go/pkg/mod/github.com/rafaelespinoza/godfish@v0.0.0-20200122053657-81bb649862dd/godfish.go:516 +0x73
github.com/rafaelespinoza/godfish.Info(0x72d160, 0xc00009a000, 0xc0000143bc, 0x4, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/rafaelespinoza/godfish@v0.0.0-20200122053657-81bb649862dd/godfish.go:481 +0x11c
github.com/rafaelespinoza/godfish/internal/commands.glob..func6(0x6d31e1, 0xd, 0x0, 0x6d19dd, 0x7, 0x72aa60, 0xc0000481e0, 0xc0000143bc, 0x4, 0x0, ...)
        /go/pkg/mod/github.com/rafaelespinoza/godfish@v0.0.0-20200122053657-81bb649862dd/internal/commands/commands.go:264 +0x10e
github.com/rafaelespinoza/godfish/internal/commands.Run(0x72aa60, 0xc0000481e0, 0x0, 0x0)
        /go/pkg/mod/github.com/rafaelespinoza/godfish@v0.0.0-20200122053657-81bb649862dd/internal/commands/commands.go:50 +0x142
main.main()
        /go/pkg/mod/github.com/rafaelespinoza/godfish@v0.0.0-20200122053657-81bb649862dd/mysql/godfish/main.go:13 +0x41
```

The same thing would happen if the path to files option was specified through a CLI flag, like

```
./godfish -files . info
```

**Comment by rafaelespinoza** [comment]
closed by #2
